name = "Ledger"
uuid = "f93f0fa3-31aa-431a-8451-47035ba470b3"
authors = ["arj <arj@workingdoge.net> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
